version: '3.8'

services:
  translation-admin:
    build: .
    ports:
      - "6300:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - translation-network

networks:
  translation-network:
    driver: bridge